"""
Seed data for LearnHub: 6 courses, each with 3 difficulty-tiered materials
and 3 quiz levels of 15 questions apiece (45 questions per course, 270 total).

Kept separate from database.py so the schema/seeding logic stays readable.
"""

SAMPLE_COURSES = [
    ("Python Programming Fundamentals",
     "Learn Python from scratch: variables, loops, functions, and object-oriented programming.",
     "6 weeks", "Dr. Ananya Rao"),
    ("Full-Stack Web Development",
     "Build complete web applications using Flask, HTML, CSS and SQL databases.",
     "8 weeks", "Michael Chen"),
    ("Database Design & SQL",
     "Master relational database design, normalization, and writing efficient SQL queries.",
     "4 weeks", "Priya Nair"),
    ("Data Structures & Algorithms",
     "Core computer science concepts every developer needs: arrays, trees, graphs and sorting.",
     "10 weeks", "James Okoro"),
    ("Cloud Computing Fundamentals",
     "Understand cloud service models, virtualization, storage, networking, and modern deployment patterns.",
     "6 weeks", "Sofia Martinez"),
    ("UI/UX Design Principles",
     "Design usable, accessible interfaces: research, wireframing, prototyping, and design systems.",
     "5 weeks", "Daniel Kim"),
]

# title, url, difficulty ('easy' | 'medium' | 'hard')
SAMPLE_MATERIALS = {
    "Python Programming Fundamentals": [
        ("Python Official Beginner's Guide", "https://docs.python.org/3/tutorial/introduction.html", "easy"),
        ("Python Functions & Data Structures Guide", "https://docs.python.org/3/tutorial/datastructures.html", "medium"),
        ("Python Classes Deep Dive", "https://docs.python.org/3/tutorial/classes.html", "hard"),
    ],
    "Full-Stack Web Development": [
        ("HTML Basics — MDN Web Docs", "https://developer.mozilla.org/en-US/docs/Learn/HTML", "easy"),
        ("Flask Quickstart Guide", "https://flask.palletsprojects.com/en/latest/quickstart/", "medium"),
        ("Flask Security Best Practices", "https://flask.palletsprojects.com/en/latest/security/", "hard"),
    ],
    "Database Design & SQL": [
        ("SQL Basics — W3Schools", "https://www.w3schools.com/sql/", "easy"),
        ("SQL Joins Explained — PostgreSQL Docs", "https://www.postgresql.org/docs/current/tutorial-join.html", "medium"),
        ("Database Schema & Normalization Guide", "https://www.postgresql.org/docs/current/ddl.html", "hard"),
    ],
    "Data Structures & Algorithms": [
        ("Big-O Notation Primer — GeeksforGeeks", "https://www.geeksforgeeks.org/analysis-of-algorithms-set-1-asymptotic-analysis/", "easy"),
        ("Sorting Algorithms Overview", "https://www.geeksforgeeks.org/sorting-algorithms/", "medium"),
        ("Graph Algorithms Deep Dive", "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/", "hard"),
    ],
    "Cloud Computing Fundamentals": [
        ("What Is Cloud Computing? — AWS", "https://aws.amazon.com/what-is-cloud-computing/", "easy"),
        ("Amazon EC2 User Guide", "https://docs.aws.amazon.com/ec2/index.html", "medium"),
        ("Kubernetes Documentation", "https://kubernetes.io/docs/home/", "hard"),
    ],
    "UI/UX Design Principles": [
        ("The Definition of User Experience — NN/g", "https://www.nngroup.com/articles/definition-user-experience/", "easy"),
        ("Ten Usability Heuristics for UI Design", "https://www.nngroup.com/articles/ten-usability-heuristics/", "medium"),
        ("Web Content Accessibility Guidelines (WCAG)", "https://www.w3.org/WAI/standards-guidelines/wcag/", "hard"),
    ],
}

# course -> level (1/2/3) -> list of (question, option1, option2, option3, option4, correct_option_number 1-4)
SAMPLE_QUIZZES = {
    "Python Programming Fundamentals": {
        1: [
            ("Which keyword defines a function in Python?", "func", "def", "function", "lambda", 2),
            ("What is the result of 7 // 2 in Python?", "3.5", "3", "4", "Error", 2),
            ("Which method adds an item to the end of a list?", "add()", "insert()", "append()", "push()", 3),
            ("Which of these is a valid Python variable name?", "2total", "my-var", "my_var", "class", 3),
            ("What data type does 5 / 2 return in Python 3?", "int", "float", "str", "bool", 2),
            ("Which symbol starts a comment in Python?", "//", "#", "<!--", "**", 2),
            ("What does len(\"hello\") return?", "4", "5", "6", "Error", 2),
            ("Which keyword starts a conditional statement?", "when", "if", "check", "switch", 2),
            ("What is the correct syntax to loop over a list called items?", "for item in items:", "loop item in items:", "for (item : items)", "foreach item in items:", 1),
            ("Which of these data types is mutable?", "tuple", "str", "list", "int", 3),
            ("How do you add a key-value pair to dictionary d?", "d.add(key, value)", "d[key] = value", "d.push(key, value)", "d.insert(key, value)", 2),
            ("What type does input() always return?", "int", "float", "str", "bool", 3),
            ("Which operator checks if two values are equal?", "=", "==", "eq", "===", 2),
            ("What is the boolean value of an empty list in an if statement?", "True", "False", "Error", "None", 2),
            ("Which keyword exits a loop immediately?", "stop", "exit", "break", "return", 3),
        ],
        2: [
            ("What does *args let a function accept?", "A single keyword argument", "A variable number of positional arguments", "A variable number of keyword arguments", "Nothing extra", 2),
            ("What does **kwargs let a function accept?", "A variable number of keyword arguments", "A variable number of positional arguments", "A single positional argument", "Nothing extra", 1),
            ("Which of these is a valid list comprehension?", "[x for x in range(10)]", "list(x for 10)", "for x in range(10) [x]", "{x in range(10)}", 1),
            ("Which built-in function pairs elements from two iterables?", "pair()", "zip()", "combine()", "link()", 2),
            ("Which keyword is used to catch an exception?", "catch", "except", "rescue", "handle", 2),
            ("Which list method removes and returns the last item?", "remove()", "delete()", "pop()", "drop()", 3),
            ("What is the correct syntax for a dictionary comprehension?", "{k: v for k, v in items}", "[k: v for k, v in items]", "(k: v for k, v in items)", "{k, v for k, v in items}", 1),
            ("Which built-in function opens a file?", "file()", "open()", "read()", "load()", 2),
            ("What best describes a Python tuple?", "A mutable ordered sequence", "An immutable ordered sequence", "A key-value mapping", "An unordered unique collection", 2),
            ("What does the `with` statement primarily help manage?", "Loops", "Resources/context, closing them automatically", "Exceptions only", "Function scope", 2),
            ("Which string method splits a string into a list?", "split()", "divide()", "cut()", "partition_all()", 1),
            ("What does enumerate() return when looping over a list?", "Just the values", "Just the indexes", "Index-value pairs", "A dictionary", 3),
            ("What Python type stores only unique, unordered values?", "list", "tuple", "set", "dict", 3),
            ("Which exception is raised when dividing a number by zero?", "ValueError", "ZeroDivisionError", "TypeError", "ArithmeticError", 2),
            ("What does `self` refer to inside an instance method?", "The class itself", "The current instance of the class", "A global variable", "The parent class", 2),
        ],
        3: [
            ("What does the @staticmethod decorator do?", "Defines a method requiring self", "Defines a method that doesn't need self/instance access", "Makes a method private", "Caches the method's result", 2),
            ("What is a Python generator?", "A class that generates random numbers", "A function that lazily yields values using `yield`", "A built-in module", "A type of loop", 2),
            ("What does MRO stand for in Python?", "Module Resolution Order", "Method Resolution Order", "Memory Reference Object", "Multiple Return Objects", 2),
            ("Which magic method controls how print() displays an object?", "__repr__ only", "__str__", "__display__", "__print__", 2),
            ("What is a Python decorator?", "A syntax error checker", "A function that wraps another function to extend its behavior", "A type of loop", "A built-in data type", 2),
            ("What does GIL stand for in CPython?", "Global Interpreter Lock", "General Import Library", "Global Instance Loader", "Grouped Iterator List", 1),
            ("Which built-in function applies a function to every item of an iterable?", "map()", "apply()", "each()", "loop()", 1),
            ("What is the purpose of __init__ in a class?", "Deletes an instance", "Initializes a new instance's attributes", "Converts an object to a string", "Compares two instances", 2),
            ("Which keyword lets a generator function produce a value and pause?", "return", "yield", "pause", "emit", 2),
            ("What two methods does the context manager protocol require?", "__start__ and __stop__", "__open__ and __close__", "__enter__ and __exit__", "__init__ and __del__", 3),
            ("In multiple inheritance, what determines which parent method runs?", "Alphabetical order", "Method Resolution Order (C3 linearization)", "File load order", "Random selection", 2),
            ("What does functools.reduce do?", "Removes duplicates from a list", "Cumulatively applies a function to reduce an iterable to one value", "Sorts an iterable", "Filters items from a list", 2),
            ("Which statement about lists vs tuples is true?", "Both are mutable", "Both are immutable", "Lists are mutable, tuples are immutable", "Tuples are mutable, lists are immutable", 3),
            ("What is a lambda function?", "A named multi-line function", "An anonymous inline function", "A class constructor", "A type of loop", 2),
            ("What does the @property decorator do in a class?", "Makes an attribute private", "Turns a method into a read-only attribute-like accessor", "Deletes an attribute", "Creates a static variable", 2),
        ],
    },
    "Full-Stack Web Development": {
        1: [
            ("What does HTML stand for?", "HyperText Markup Language", "HighText Machine Language", "HyperTransfer Markup Language", "HyperText Modern Language", 1),
            ("Which tag creates a hyperlink in HTML?", "<link>", "<a>", "<href>", "<nav>", 2),
            ("Which CSS property changes text color?", "text-color", "font-color", "color", "fg-color", 3),
            ("What does CSS stand for?", "Creative Style Sheets", "Cascading Style Sheets", "Computer Style Syntax", "Colored Style Sheets", 2),
            ("What is the root element of an HTML document?", "<body>", "<root>", "<html>", "<doc>", 3),
            ("Which HTTP method retrieves data from a server?", "GET", "SEND", "FETCH", "PULL", 1),
            ("In Flask, which decorator defines a URL route?", "@app.url()", "@app.route()", "@app.path()", "@app.link()", 2),
            ("What does HTTP stand for?", "HyperText Transfer Protocol", "High Transfer Text Protocol", "HyperText Terminal Program", "Host Transfer Text Protocol", 1),
            ("Which tag embeds an image in HTML?", "<image>", "<pic>", "<img>", "<src>", 3),
            ("Which HTTP method is typically used to submit form data?", "GET", "POST", "PUT", "HEAD", 2),
            ("What is the purpose of the <head> tag in HTML?", "Displays the page title on screen", "Contains metadata about the document", "Holds the main visible content", "Defines the footer", 2),
            ("Which CSS selector targets an element by class?", "#classname", ".classname", "*classname", "@classname", 2),
            ("What does a web server do at a basic level?", "Writes CSS files", "Responds to client requests with resources or data", "Compiles Python code", "Stores emails only", 2),
            ("Which port does HTTP use by default?", "21", "80", "443", "8080", 2),
            ("What is the typical file extension of a Flask application's main file?", ".flask", ".html", ".py", ".web", 3),
        ],
        2: [
            ("What templating engine does Flask use by default?", "Mako", "Jinja2", "Handlebars", "Django Templates", 2),
            ("Which Jinja2 syntax starts a for loop?", "{% for x in list %}", "{{ for x in list }}", "<for x in list>", "[for x in list]", 1),
            ("What does REST stand for?", "Representational State Transfer", "Remote Execution Service Transfer", "Rapid State Transition", "Resource Exchange State Type", 1),
            ("Which HTTP status code means \"Not Found\"?", "200", "301", "404", "500", 3),
            ("Which HTTP status code means \"OK\"?", "100", "200", "301", "404", 2),
            ("What format is most commonly used for API request/response bodies?", "XML", "CSV", "JSON", "YAML", 3),
            ("What's the key difference between a cookie and a server-side session?", "They're identical", "Cookies are stored client-side; session data is stored server-side", "Sessions are stored client-side; cookies are stored server-side", "Cookies expire instantly", 2),
            ("Which Flask function renders an HTML template?", "render_template()", "show_template()", "load_html()", "display()", 1),
            ("Which HTTP status code indicates successful resource creation?", "200", "201", "204", "301", 2),
            ("Which HTTP method is idempotent and typically replaces a full resource?", "POST", "PATCH", "PUT", "GET", 3),
            ("What does CRUD stand for?", "Create, Read, Update, Delete", "Copy, Run, Undo, Deploy", "Create, Run, Update, Debug", "Connect, Read, Upload, Delete", 1),
            ("Which Flask object holds submitted form data?", "request.args", "request.form", "request.json", "request.data", 2),
            ("What is the purpose of a URL query string?", "To style the page", "To pass extra parameters in a GET request", "To define the HTTP method", "To store cookies", 2),
            ("Which HTTP status code range indicates client errors?", "100-199", "200-299", "300-399", "400-499", 4),
            ("What does Flask's redirect() function do?", "Renders a template twice", "Sends the client a response to navigate to another URL", "Deletes a session", "Logs an error", 2),
        ],
        3: [
            ("What does CSRF stand for?", "Cross-Site Request Forgery", "Cross-Server Resource Fetch", "Client-Side Redirect Function", "Cascading Site Reference Format", 1),
            ("What is the main purpose of a CSRF token?", "To encrypt passwords", "To verify a form submission came from the legitimate site, not a forged request", "To speed up page loads", "To compress form data", 2),
            ("What does an ORM do?", "Optimizes images automatically", "Maps database tables to objects/classes in code", "Renders HTML templates", "Manages CSS styles", 2),
            ("What does SQL injection exploit?", "Slow network speeds", "Unsanitized user input inserted directly into SQL queries", "Weak CSS selectors", "Expired cookies", 2),
            ("Which practice best prevents SQL injection?", "Using string concatenation for queries", "Using parameterized queries / prepared statements", "Disabling the database", "Hiding the login form", 2),
            ("What does WSGI stand for?", "Web Server Gateway Interface", "Website Structure Generation Index", "Web Service Group Interconnect", "Web Server General Instance", 1),
            ("What is the purpose of CORS?", "Compresses HTTP responses", "Controls which origins can access a server's resources from a browser", "Encrypts cookies", "Speeds up DNS lookups", 2),
            ("What is a JWT commonly used for?", "Styling web pages", "Stateless authentication via signed tokens", "Storing images", "Compiling JavaScript", 2),
            ("What is a key benefit of caching in web applications?", "Increases database size", "Reduces repeated computation/database load and speeds up responses", "Removes the need for a server", "Encrypts all traffic", 2),
            ("What is a key characteristic of microservices architecture?", "One giant monolithic codebase", "Independently deployable, loosely coupled services", "No use of APIs", "Single shared database only", 2),
            ("What does \"idempotent\" mean for an HTTP method?", "It only works once", "Repeating the same request produces the same result/state", "It always fails", "It requires authentication", 2),
            ("What typically sits between Flask and the internet in production?", "Nothing at all", "A WSGI server (e.g. Gunicorn) behind a reverse proxy", "A second Flask app", "A local file server", 2),
            ("Why should passwords be hashed before storage?", "To make them shorter", "To protect passwords even if the database is compromised", "To speed up login", "To allow easy recovery", 2),
            ("What does horizontal scaling mean?", "Adding more RAM to one server", "Adding more servers/instances to handle load", "Reducing server count", "Upgrading the CPU only", 2),
            ("What is a common way to prevent XSS attacks?", "Using longer passwords", "Escaping/sanitizing user-generated output before rendering", "Disabling cookies", "Using GET instead of POST", 2),
        ],
    },
    "Database Design & SQL": {
        1: [
            ("Which SQL statement retrieves data from a table?", "GET", "SELECT", "FETCH", "PULL", 2),
            ("Which clause filters rows in a SELECT query?", "FILTER", "WHERE", "HAVING", "IF", 2),
            ("What does a PRIMARY KEY guarantee for a column?", "Sorted order only", "Uniqueness and non-null values", "Faster inserts only", "Text data type", 2),
            ("Which SQL clause sorts the result set?", "SORT BY", "ORDER BY", "GROUP BY", "ARRANGE BY", 2),
            ("What is a table in a relational database?", "A single value", "A structured collection of rows and columns", "A type of index", "A saved query only", 2),
            ("Which SQL keyword inserts new data into a table?", "ADD", "INSERT", "CREATE", "NEW", 2),
            ("Which SQL keyword removes rows from a table?", "REMOVE", "DROP", "DELETE", "CLEAR", 3),
            ("Which SQL keyword changes existing data in a table?", "CHANGE", "UPDATE", "SET", "MODIFY", 2),
            ("What does NULL represent in SQL?", "Zero", "An empty string", "The absence of a value", "A boolean false", 3),
            ("Which SQL clause limits the number of rows returned?", "TOP", "LIMIT", "MAX", "CAP", 2),
            ("What is a column's data type used for?", "Naming the column", "Defining what kind of values it can store", "Sorting rows", "Creating indexes automatically", 2),
            ("Which symbol commonly selects all columns in SQL?", "%", "&", "*", "#", 3),
            ("What does DDL stand for?", "Data Definition Language", "Database Driven Logic", "Data Delivery Layer", "Direct Data Link", 1),
            ("Which statement creates a new table?", "MAKE TABLE", "NEW TABLE", "CREATE TABLE", "BUILD TABLE", 3),
            ("What does a FOREIGN KEY do?", "Encrypts a column", "Links a column to a primary key in another table for referential integrity", "Makes a column unique only", "Speeds up all queries", 2),
        ],
        2: [
            ("Which SQL clause combines rows from two tables based on a related column?", "MERGE", "JOIN", "LINK", "COMBINE", 2),
            ("What's the difference between INNER JOIN and LEFT JOIN?", "They're identical", "INNER only matches rows in both tables; LEFT keeps all left rows even without a match", "LEFT only matches rows in both tables", "INNER keeps unmatched rows", 2),
            ("Which clause filters groups after aggregation?", "WHERE", "HAVING", "GROUP BY", "FILTER", 2),
            ("Which clause filters rows before grouping?", "HAVING", "WHERE", "ORDER BY", "LIMIT", 2),
            ("Which aggregate function returns the number of rows?", "SUM()", "COUNT()", "TOTAL()", "ROWS()", 2),
            ("What does GROUP BY do?", "Sorts rows alphabetically", "Groups rows sharing a value so aggregates can be applied per group", "Deletes duplicate rows", "Creates a new table", 2),
            ("What is a subquery?", "A query stored as a view", "A query nested inside another query", "A query that only selects one column", "A backup query", 2),
            ("What does an INDEX primarily improve?", "Data encryption", "Query/lookup performance", "Column naming", "Table size", 2),
            ("Which SQL keyword removes duplicate rows from a result?", "UNIQUE", "DISTINCT", "ONLY", "SINGLE", 2),
            ("What does AVG() calculate?", "The count of rows", "The average of a numeric column", "The maximum value", "The total sum", 2),
            ("What is a composite key?", "A key made of random characters", "A primary key made up of two or more columns", "An encrypted key", "A foreign key only", 2),
            ("Which JOIN returns rows only when there's a match in both tables?", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN", 3),
            ("What does the UNIQUE constraint enforce?", "Sorted values", "No duplicate values allowed in that column", "Non-null values only", "Fixed-length values", 2),
            ("What is the purpose of an alias (AS) in SQL?", "To delete a column", "To give a table or column a temporary readable name", "To encrypt data", "To create an index", 2),
            ("Which clause combines the result sets of two SELECT statements?", "JOIN", "UNION", "MERGE", "APPEND", 2),
        ],
        3: [
            ("What does ACID stand for in database transactions?", "Atomicity, Consistency, Isolation, Durability", "Access, Control, Index, Data", "Aggregate, Commit, Insert, Delete", "Atomic, Cached, Indexed, Distributed", 1),
            ("What is database normalization primarily used for?", "Making queries slower", "Reducing data redundancy and improving data integrity", "Increasing storage requirements", "Removing all indexes", 2),
            ("What is Third Normal Form (3NF) primarily concerned with?", "Removing all foreign keys", "Removing transitive dependencies on the primary key", "Adding more indexes", "Merging all tables into one", 2),
            ("What is a deadlock in a database?", "A crashed server", "Two or more transactions waiting on each other's locks, unable to proceed", "A missing index", "A slow query", 2),
            ("What does the \"Read Committed\" isolation level prevent?", "Phantom reads", "Dirty reads", "Slow queries", "Lock contention entirely", 2),
            ("What is a database view?", "A physical copy of a table", "A saved, virtual table defined by a query", "An index on a column", "A backup file", 2),
            ("What is the main advantage of a stored procedure?", "It runs on the client only", "Precompiled, reusable logic executed on the database server", "It replaces all tables", "It removes the need for SQL", 2),
            ("What is query optimization primarily concerned with?", "Making tables bigger", "Choosing the most efficient way to execute a query", "Removing all constraints", "Disabling indexes", 2),
            ("What is a covering index?", "An index that hides sensitive data", "An index containing all columns needed to satisfy a query without hitting the table", "An index on every column", "A backup index", 2),
            ("What is the main tradeoff of adding more indexes to a table?", "No tradeoff at all", "Faster reads but slower writes/updates and more storage", "Slower reads only", "Reduced data integrity", 2),
            ("What does denormalization trade off for performance?", "Nothing, it's free", "Introduces redundancy to reduce the number of joins needed", "Removes all relationships", "Increases normalization level", 2),
            ("What does the \"Serializable\" isolation level guarantee?", "Fastest possible execution", "Transactions behave as if executed one at a time, fully isolated", "No locking is used", "Only read operations are allowed", 2),
            ("What is a key difference between SQL and NoSQL databases?", "They are the same thing", "SQL is relational with fixed schemas; NoSQL is often schema-less/flexible", "NoSQL doesn't store data", "SQL cannot use indexes", 2),
            ("What is a write-ahead log (WAL) used for?", "Logging user logins", "Recording changes before they're committed, to support crash recovery", "Storing CSS styles", "Caching query results", 2),
            ("What does sharding do in database scaling?", "Merges all data into one node", "Splits data across multiple database instances/nodes horizontally", "Encrypts the database", "Deletes old records automatically", 2),
        ],
    },
    "Data Structures & Algorithms": {
        1: [
            ("What is an array?", "A single variable", "A collection of elements stored at contiguous memory locations, accessed by index", "A type of loop", "A sorting algorithm", 2),
            ("What does Big-O notation describe?", "The exact runtime in seconds", "The growth rate of an algorithm's time or space usage", "The programming language used", "The number of bugs in code", 2),
            ("What is the time complexity of accessing an array element by index?", "O(n)", "O(log n)", "O(1)", "O(n^2)", 3),
            ("Which data structure follows Last-In-First-Out order?", "Queue", "Stack", "Array", "Tree", 2),
            ("Which data structure follows First-In-First-Out order?", "Stack", "Queue", "Heap", "Graph", 2),
            ("What is a linked list node typically made of?", "Only data", "Data and a pointer/reference to the next node", "Only a pointer", "An index and a key", 2),
            ("What is the worst-case time complexity of linear search?", "O(1)", "O(log n)", "O(n)", "O(n^2)", 3),
            ("What does \"in-place\" mean for a sorting algorithm?", "It uses a second array of equal size", "It sorts data without needing significant extra memory", "It only works on sorted data", "It sorts in reverse order", 2),
            ("What is recursion?", "A loop that never ends", "A function calling itself to solve smaller subproblems", "A sorting technique", "A type of array", 2),
            ("What is the time complexity of binary search on a sorted array?", "O(n)", "O(log n)", "O(1)", "O(n log n)", 2),
            ("Which operation adds an element to the top of a stack?", "enqueue", "push", "pop", "insert", 2),
            ("Which operation removes an element from a queue?", "push", "pop", "dequeue", "peek", 3),
            ("What does an algorithm's space complexity describe?", "Its runtime speed", "How much extra memory it uses relative to input size", "The number of functions used", "Its code length", 2),
            ("What is a base case in recursion?", "The first line of any function", "The condition that stops further recursive calls", "An error condition", "A loop counter", 2),
            ("What is the worst-case time to access an element by position in a singly linked list?", "O(1)", "O(log n)", "O(n)", "O(n^2)", 3),
        ],
        2: [
            ("What is the average time complexity of quicksort?", "O(n)", "O(n log n)", "O(n^2)", "O(log n)", 2),
            ("What is the worst-case time complexity of quicksort?", "O(n log n)", "O(n)", "O(n^2)", "O(log n)", 3),
            ("Which sorting algorithm repeatedly swaps adjacent out-of-order elements?", "Merge sort", "Bubble sort", "Quicksort", "Heap sort", 2),
            ("What is the time complexity of merge sort in all cases?", "O(n)", "O(n^2)", "O(n log n)", "O(log n)", 3),
            ("What underlies a hash table for storing key-value pairs?", "A linked list only", "An array of buckets indexed by a hash function", "A binary tree", "A stack", 2),
            ("What is a hash collision?", "A server crash", "When two different keys map to the same hash/bucket", "An invalid key", "A full hash table", 2),
            ("What is the average time complexity of a hash table lookup?", "O(n)", "O(log n)", "O(1)", "O(n log n)", 3),
            ("What is a binary tree?", "A tree with exactly two nodes", "A tree where each node has at most two children", "A sorted array", "A type of hash table", 2),
            ("What is a binary search tree's key property?", "All nodes have the same value", "Left subtree values are smaller, right subtree values are larger than the node", "It has no root", "It's always balanced", 2),
            ("What does recursion require to avoid infinite calls?", "A loop counter", "A well-defined base case", "A global variable", "A sorted array", 2),
            ("What is the time complexity of inserting at the head of a linked list?", "O(n)", "O(log n)", "O(1)", "O(n^2)", 3),
            ("Which sorting algorithm divides the array and merges sorted halves?", "Bubble sort", "Insertion sort", "Merge sort", "Selection sort", 3),
            ("What is in-order traversal of a BST typically used for?", "Reversing the tree", "Visiting nodes in ascending sorted order", "Deleting all nodes", "Finding the tree's height only", 2),
            ("What is the height of a balanced binary tree with n nodes approximately?", "O(n)", "O(log n)", "O(n^2)", "O(1)", 2),
            ("What does binary search require of its input?", "It must be a linked list", "The data must be sorted", "It must contain unique values only", "It must be a hash table", 2),
        ],
        3: [
            ("What does Breadth-First Search (BFS) use internally to traverse a graph?", "A stack", "A queue", "A hash table", "Recursion only", 2),
            ("What does Depth-First Search (DFS) typically use internally?", "A queue", "A stack (or recursion)", "A hash table", "A heap", 2),
            ("What problem does Dijkstra's algorithm solve?", "Sorting an array", "Shortest path from a source to all other nodes in a weighted graph with non-negative weights", "Finding a hash collision", "Balancing a binary tree", 2),
            ("What is dynamic programming primarily used for?", "Random number generation", "Solving problems by breaking them into overlapping subproblems and caching results", "Sorting linked lists", "Encrypting data", 2),
            ("What is memoization?", "Deleting old cache entries", "Caching results of expensive function calls to avoid recomputation", "A sorting technique", "A graph traversal method", 2),
            ("What property must a graph have for Dijkstra's algorithm to work correctly?", "It must be a tree", "Non-negative edge weights", "It must be undirected", "It must be acyclic", 2),
            ("What is a greedy algorithm?", "An algorithm that tries every possibility", "An algorithm that makes the locally optimal choice at each step", "An algorithm that always uses recursion", "An algorithm with O(1) time complexity", 2),
            ("What is a self-balancing binary search tree used for?", "Reducing memory usage to zero", "Keeping operations at O(log n) by maintaining balanced height", "Removing the need for a root node", "Storing only integers", 2),
            ("What is a min-heap's key property?", "The parent node is always larger than its children", "The parent node is always smaller than or equal to its children", "All leaves are equal", "It's always a linked list", 2),
            ("What is the time complexity of building a heap from an array (heapify)?", "O(n log n)", "O(n^2)", "O(n)", "O(log n)", 3),
            ("What does the term \"NP-complete\" describe?", "A problem with no verifiable solution", "A class of problems with no known efficient solution, but solutions are verifiable quickly", "A problem solvable in O(1) time", "A sorting algorithm", 2),
            ("What is a topological sort used for?", "Sorting numbers in a list", "Ordering nodes in a Directed Acyclic Graph so dependencies come before dependents", "Balancing a binary tree", "Finding the shortest path", 2),
            ("What is the space-time tradeoff in dynamic programming with memoization?", "Uses less memory and less time", "Uses extra memory to reduce time complexity", "Uses no memory at all", "Has no effect on performance", 2),
            ("What distinguishes an AVL tree from a regular BST?", "It stores only strings", "It automatically rebalances to keep height differences small", "It has no root node", "It cannot be traversed", 2),
            ("What is the time complexity of extracting the minimum from a min-heap?", "O(1)", "O(log n)", "O(n)", "O(n log n)", 2),
        ],
    },
    "Cloud Computing Fundamentals": {
        1: [
            ("What does IaaS stand for?", "Internet as a Service", "Infrastructure as a Service", "Instance as a Service", "Integration as a Service", 2),
            ("What does PaaS stand for?", "Platform as a Service", "Product as a Service", "Provider as a Service", "Process as a Service", 1),
            ("What does SaaS stand for?", "Server as a Service", "Software as a Service", "Storage as a Service", "System as a Service", 2),
            ("What is cloud computing?", "Buying physical servers for an office", "On-demand delivery of computing resources over the internet", "A type of programming language", "A local network protocol", 2),
            ("Which of these is a public cloud provider?", "Amazon Web Services (AWS)", "Microsoft Word", "Adobe Photoshop", "VLC Media Player", 1),
            ("What is virtualization?", "Making a website look 3D", "Creating virtual versions of computing resources like servers using software", "Compressing files", "Encrypting network traffic", 2),
            ("What is a private cloud?", "A cloud used by the general public", "Cloud infrastructure used exclusively by one organization", "A free cloud tier", "A local hard drive", 2),
            ("What is a hybrid cloud?", "A cloud that only stores images", "A combination of private and public cloud infrastructure", "A cloud with no internet access", "A single-server setup", 2),
            ("What is the main benefit of cloud elasticity?", "Resources never change", "Resources can scale up or down automatically based on demand", "It removes the need for security", "It guarantees zero cost", 2),
            ("What is a Virtual Machine (VM)?", "A physical computer only", "A software emulation of a physical computer", "A type of database", "A network cable", 2),
            ("What best describes \"pay-as-you-go\" pricing?", "A fixed yearly fee regardless of usage", "You pay only for the resources you actually use", "Free for the first year only", "A one-time lifetime payment", 2),
            ("What does a Content Delivery Network (CDN) do?", "Deletes old content automatically", "Distributes content across servers closer to users to reduce latency", "Encrypts all databases", "Compiles source code", 2),
            ("What is on-premises infrastructure?", "Infrastructure rented from a cloud provider", "Hardware and software hosted physically at an organization's own location", "A mobile app", "A type of firewall", 2),
            ("What does SaaS provide to end users?", "Raw virtual machines", "Ready-to-use software accessed over the internet, no installation needed", "Physical servers", "Networking cables", 2),
            ("What is the main role of a hypervisor?", "Compiles application code", "Creates and manages virtual machines on physical hardware", "Sends emails", "Stores backups only", 2),
        ],
        2: [
            ("What is Amazon EC2 primarily used for?", "Sending emails", "Running virtual servers (compute instances) in the cloud", "Storing photos only", "Managing DNS records only", 2),
            ("What is object storage best suited for?", "Low-latency disk access for a single VM", "Storing large amounts of unstructured data like files and backups", "Running databases directly", "Real-time video processing only", 2),
            ("What is block storage typically used for?", "Static website hosting", "Attached storage for VMs needing low-latency disk-like access", "Sending notifications", "DNS resolution", 2),
            ("What does a load balancer do?", "Encrypts all traffic", "Distributes incoming traffic across multiple servers", "Deletes unused servers", "Compiles application code", 2),
            ("What is auto-scaling?", "Manually adding servers once a year", "Automatically adjusting the number of running instances based on demand", "A backup strategy", "A type of firewall rule", 2),
            ("What is a VPC (Virtual Private Cloud)?", "A physical private server room", "An isolated virtual network within a cloud provider for your resources", "A type of load balancer", "A billing dashboard", 2),
            ("What is a cloud \"region\"?", "A single server", "A geographic area containing multiple data centers", "A type of firewall", "A pricing tier", 2),
            ("What is an \"availability zone\"?", "A billing region", "An isolated data center location within a region for fault tolerance", "A type of VPN", "A backup schedule", 2),
            ("What is the purpose of a security group in cloud networking?", "Stores passwords", "Acts as a virtual firewall controlling inbound/outbound traffic", "Compiles code", "Encrypts hard drives only", 2),
            ("What is the benefit of using multiple availability zones?", "Lower cost only", "Improves fault tolerance and high availability", "Faster code compilation", "Simpler billing", 2),
            ("What is a snapshot in cloud storage?", "A live database connection", "A point-in-time backup copy of a disk/volume", "A type of virtual machine", "A network diagram", 2),
            ("What does DNS do in a cloud architecture?", "Encrypts network traffic", "Translates domain names into IP addresses", "Balances server load", "Stores files permanently", 2),
            ("What's the difference between vertical and horizontal scaling?", "They are identical", "Vertical adds resources to one server; horizontal adds more servers", "Horizontal adds resources to one server; vertical adds more servers", "Neither adds capacity", 2),
            ("What is a subnet used for in a VPC?", "Encrypting traffic", "Dividing a network into smaller segments for organization and security", "Hosting a website", "Running containers", 2),
            ("What is latency in networking?", "The total storage capacity", "The delay between a request and its response", "The number of servers online", "The cost of a service", 2),
        ],
        3: [
            ("What is a container (e.g., Docker)?", "A full virtual machine with its own OS kernel", "A lightweight, portable package containing an app and its dependencies", "A type of physical server", "A billing unit", 2),
            ("What does Kubernetes primarily manage?", "Email delivery", "Orchestration and scaling of containerized applications", "DNS records only", "Credit card billing", 2),
            ("What is serverless computing?", "Computing with no internet connection", "Running code without managing the underlying servers, billed per execution", "A type of on-premises server", "A deprecated technology", 2),
            ("What does IAM stand for in cloud security?", "Internet Access Management", "Identity and Access Management", "Instance Allocation Manager", "Infrastructure Automation Module", 2),
            ("What is the principle of least privilege?", "Giving all users admin access", "Granting users only the permissions they need to do their job, nothing more", "Disabling all permissions", "Sharing one account for everyone", 2),
            ("What is CI/CD?", "A cloud pricing model", "Continuous Integration and Continuous Deployment/Delivery, automating build/test/release", "A type of database", "A security certificate", 2),
            ("What is a disaster recovery plan primarily concerned with?", "Preventing all outages permanently", "Restoring systems and data after a major failure or outage", "Reducing monthly costs", "Improving UI design", 2),
            ("What does \"multi-cloud\" mean?", "Using multiple accounts on one provider", "Using services from more than one cloud provider", "Using only on-premises servers", "A single very large server", 2),
            ("What is a key benefit of microservices architecture in the cloud?", "A single point of failure", "Independent scaling and deployment of individual services", "Requires no networking", "Eliminates the need for testing", 2),
            ("What is cost optimization in cloud computing primarily about?", "Always choosing the cheapest option regardless of performance", "Reducing unnecessary spend while meeting performance needs", "Disabling monitoring", "Removing all backups", 2),
            ("What is an Infrastructure as Code (IaC) tool used for?", "Writing frontend UI code", "Defining and provisioning infrastructure using machine-readable config files", "Compiling mobile apps", "Sending marketing emails", 2),
            ("What does a Kubernetes \"pod\" represent?", "An entire physical server", "The smallest deployable unit, usually one or more tightly coupled containers", "A billing account", "A DNS record", 2),
            ("What is encryption at rest?", "Encrypting data only while it travels over a network", "Encrypting stored data so it's unreadable without the decryption key", "Turning off encryption during backups", "A type of load balancer", 2),
            ("What is the shared responsibility model in cloud security?", "The customer secures everything", "Cloud provider secures the infrastructure; customer secures their data/config/access", "The cloud provider secures everything with no customer involvement", "There is no shared responsibility", 2),
            ("What does \"immutable infrastructure\" mean?", "Servers that are frequently patched in place", "Servers are never modified after deployment; changes are made by replacing them", "Infrastructure that cannot be deleted", "A type of encryption", 2),
        ],
    },
    "UI/UX Design Principles": {
        1: [
            ("What does UX stand for?", "User Experience", "User Extension", "Unified Experience", "User Exchange", 1),
            ("What does UI stand for?", "User Interface", "Unified Interface", "User Integration", "Universal Icon", 1),
            ("What's the main difference between UX and UI?", "They are identical", "UX focuses on the overall experience/usability; UI focuses on visual interface elements", "UI focuses on backend code", "UX only concerns colors", 2),
            ("What is a wireframe?", "A finished, polished design", "A simple, low-fidelity layout sketch of a screen's structure", "A type of font", "A marketing document", 2),
            ("What is the purpose of contrast in visual design?", "To make text harder to read", "To make elements distinguishable and improve readability", "To reduce file size", "To add animation", 2),
            ("What is typography in design?", "The study of colors", "The art and technique of arranging and styling text", "A layout grid system", "A type of icon", 2),
            ("What is whitespace (negative space) used for in design?", "Filling empty pixels randomly", "Improving clarity, focus, and reducing visual clutter", "Adding more text", "Increasing load time", 2),
            ("What is a color palette?", "A single random color", "A selected set of colors used consistently throughout a design", "A type of font", "A CSS file", 2),
            ("What is a mockup in design?", "A rough sketch on paper only", "A high-fidelity visual representation of a design, close to the final look", "Backend server code", "A user research report", 2),
            ("What is alignment in design principles used for?", "Randomizing element positions", "Creating visual order and connections between elements", "Choosing colors", "Writing copy", 2),
            ("What design principle refers to grouping related items together?", "Contrast", "Proximity", "Repetition", "Alignment", 2),
            ("What is the purpose of a call-to-action (CTA) button?", "To decorate the page", "To prompt the user to take a specific action", "To display the logo", "To load the footer", 2),
            ("What does \"responsive design\" mean?", "A design that only works on desktop", "A design that adapts to different screen sizes and devices", "A design with fast animations", "A design using bright colors", 2),
            ("What is a font pairing?", "Using only one font everywhere", "Combining two complementary fonts, often for headings and body text", "A type of color scheme", "A CSS animation", 2),
            ("What is visual hierarchy?", "Randomly sizing elements", "Arranging elements to show their order of importance to the viewer", "Using only black and white", "A type of navigation menu", 2),
        ],
        2: [
            ("What is a user persona?", "A real user's legal name", "A fictional profile representing a segment of real users, based on research", "A password policy", "A type of wireframe", 2),
            ("What is usability testing?", "Testing server load capacity", "Observing real users interacting with a product to identify problems", "Testing code for bugs only", "A marketing survey", 2),
            ("What are Nielsen's usability heuristics?", "A programming language", "A set of general principles for evaluating interface usability", "A color theory model", "A type of database", 2),
            ("What is information architecture?", "The physical server layout", "The organization and structure of content within a product", "A font pairing technique", "A CSS framework", 2),
            ("What is a user journey map?", "A geographic map of users", "A visualization of the steps a user takes to accomplish a goal", "A sitemap of URLs only", "A list of bugs", 2),
            ("What is A/B testing used for in design?", "Testing server uptime", "Comparing two versions of a design to see which performs better", "Testing two different databases", "Debugging JavaScript", 2),
            ("What is a low-fidelity prototype?", "A finished production app", "An early, simple, often non-interactive version of a design", "A backend API", "A marketing brochure", 2),
            ("What is a high-fidelity prototype?", "A rough pencil sketch", "A detailed, interactive prototype closely resembling the final product", "A written requirements doc", "A server configuration file", 2),
            ("What is the purpose of user research?", "To finalize the visual theme first", "To understand user needs, behaviors, and pain points before designing", "To write backend code", "To choose a hosting provider", 2),
            ("What is accessibility in design concerned with?", "Only visual aesthetics", "Making products usable by people with a wide range of abilities and disabilities", "Reducing server costs", "Increasing page load speed only", 2),
            ("What is a card sorting exercise used for?", "Organizing a deck of playing cards", "Understanding how users categorize and group information", "Testing server performance", "Choosing brand colors", 2),
            ("What does Fitts's Law describe?", "Server response time", "The time to reach a target depends on its size and distance", "Color contrast ratios", "Database query speed", 2),
            ("What is a heuristic evaluation?", "A user survey", "An expert review of an interface against established usability principles", "A performance benchmark", "A legal audit", 2),
            ("What is the purpose of a style guide in UI design?", "To document server APIs", "To ensure visual and interaction consistency across a product", "To store user passwords", "To track bug reports", 2),
            ("What is affordance in UX design?", "A pricing discount", "A visual cue suggesting how an object should be used (e.g., a button looks clickable)", "A backend database field", "A legal disclaimer", 2),
        ],
        3: [
            ("What is a design system?", "A single Photoshop file", "A comprehensive set of reusable components, guidelines, and standards for consistent design", "A server hosting plan", "A marketing campaign", 2),
            ("What does WCAG stand for?", "Web Content Accessibility Guidelines", "World Content Analysis Group", "Web Coding and Graphics", "Website Component Access Guide", 1),
            ("What is the minimum recommended contrast ratio for normal text under WCAG AA?", "2:1", "3:1", "4.5:1", "7:1", 3),
            ("What are the typical stages of the design thinking process?", "Plan, Code, Test, Deploy", "Empathize, Define, Ideate, Prototype, Test", "Design, Build, Ship, Monitor", "Research, Write, Edit, Publish", 2),
            ("What's a common interaction pattern for revealing extra content without navigation?", "A full page reload", "An accordion or expandable panel", "A 404 error page", "A CAPTCHA", 2),
            ("What is progressive disclosure in UX design?", "Showing all information at once", "Showing only essential information first, revealing more as needed", "Hiding all navigation permanently", "Displaying ads progressively", 2),
            ("What is the goal of mobile-first design?", "Designing only for desktops", "Designing for the smallest screen first, then enhancing for larger screens", "Ignoring responsive layouts", "Using only native mobile apps", 2),
            ("Who typically performs a heuristic evaluation?", "Random end users", "Usability experts, not end users", "Backend developers only", "Marketing teams only", 2),
            ("What does \"cognitive load\" refer to in UX?", "Server processing load", "The amount of mental effort required to use an interface", "Page load time in seconds", "Database query complexity", 2),
            ("What is skeuomorphism in design?", "A minimalist flat design style", "Design that mimics real-world objects' appearance and textures", "A type of coding pattern", "A backend architecture", 2),
            ("What is the purpose of atomic design methodology?", "Splitting servers into smaller units", "Building UI from small reusable pieces (atoms) up to complex structures", "Reducing atomic-level code bugs", "A database normalization technique", 2),
            ("What is a dark pattern in UX design?", "A design using a dark color theme", "A deceptive design choice that manipulates users into unintended actions", "A nighttime-only feature", "An accessibility improvement", 2),
            ("What's the difference between qualitative and quantitative UX research?", "They are the same", "Qualitative explores why/how through observation; quantitative measures what/how much through data", "Quantitative is always better", "Qualitative only uses surveys", 2),
            ("What does \"consistency\" as a usability heuristic help reduce?", "Server costs", "The learning curve, since users can apply prior knowledge", "Page load time", "Color variety", 2),
            ("What is the purpose of conducting a competitive analysis in UX design?", "To copy a competitor's code", "To understand strengths/weaknesses of similar existing products", "To reduce hosting costs", "To write backend tests", 2),
        ],
    },
}
